#######################
#### ===spring===
#######################
spring:
  devtools:
    restart:
      # 设置需要排除的文件
      exclude: static/**,public/**
      # 热部署生效
      enabled: true
      # 设置重启的目录,添加那个目录的文件需要restart
      additional-paths: src/main/java
  thymeleaf:
    # 开发配置为false,避免修改模板还要重启服务器
    cache: false
  ### redis
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    # 连接超时时间（毫秒）
    # timeout: 10000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 5
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        # max-wait: -1
#######################
#### ===logging===
#######################
logging:
  config: classpath:log/logback.xml
  # 日志路径
  path: E:\log\bootdo

#######################
#### ===swagger2===
#######################
swagger:
  # 开启swagger功能
  enable: true
