#######################
#### ===公共配置===
#######################
server:
  port: 80
  tomcat:
    uri-encoding: utf-8
#  servlet:
#    context-path: /bootdo


#######################
#### ===spring===
#######################
spring:
  # thymeleaf 相关配置
  thymeleaf:
    # 生产环境开启模板缓存
    cache: true

#######################
#### ===logging===
#######################
logging:
  config: classpath:log/logback.xml
  # 日志路径
  path: E:\log\bootdo

#######################
#### ===swagger2===
#######################
swagger:
  # 关闭swagger功能
  enable: false